service: express-app

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 1536

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: 
            origin: "*"
            headers:
              - Content-Type
              - X-Requested-With
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - auth-token
      - http:
          path: /{proxy+}
          method: ANY
          cors: 
            origin: "*"
            headers:
              - Content-Type
              - X-Requested-With
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - auth-token

plugins:
  - serverless-offline